export const ALL_ANIMALS_REQUEST = 'ALL_ANIMALS_REQUEST'
export const ALL_ANIMALS_SUCCESS = 'ALL_ANIMALS_SUCCESS'
export const ALL_ANIMALS_FAIL = 'ALL_ANIMALS_FAIL'

export const FULL_ANIMALS_REQUEST = 'FULL_ANIMALS_REQUEST'
export const FULL_ANIMALS_SUCCESS = 'FULL_ANIMALS_SUCCESS'
export const FULL_ANIMALS_FAIL = 'FULL_ANIMALS_FAIL'

export const ANIMAL_DETAILS_REQUEST = 'ANIMAL_DETAILS_REQUEST'
export const ANIMAL_DETAILS_SUCCESS = 'ANIMAL_DETAILS_SUCCESS'
export const ANIMAL_DETAILS_FAIL = 'ANIMAL_DETAILS_FAIL'

export const SINGLE_DETAILS_REQUEST = 'SINGLE_DETAILS_REQUEST'
export const SINGLE_DETAILS_SUCCESS = 'SINGLE_DETAILS_SUCCESS'
export const SINGLE_DETAILS_FAIL = 'SINGLE_DETAILS_FAIL'

export const NEW_ANIMALS_REQUEST = 'NEW_ANIMALS_REQUEST'
export const NEW_ANIMALS_SUCCESS = 'NEW_ANIMALS_SUCCESS'
export const NEW_ANIMALS_RESET = 'NEW_ANIMALS_RESET'
export const NEW_ANIMALS_FAIL = 'NEW_ANIMALS_FAIL'

export const ADOPT_ANIMALS_REQUEST = 'ADOPT_ANIMALS_REQUEST'
export const ADOPT_ANIMALS_SUCCESS = 'ADOPT_ANIMALS_SUCCESS'
export const ADOPT_ANIMALS_RESET = 'ADOPT_ANIMALS_RESET'
export const ADOPT_ANIMALS_FAIL = 'ADOPT_ANIMALS_FAIL'

export const GET_ADOPT_REQUEST = 'GET_ADOPT_REQUEST'
export const GET_ADOPT_SUCCESS = 'GET_ADOPT_SUCCESS'
export const GET_ADOPT_RESET = 'GET_ADOPT_RESET'
export const GET_ADOPT_FAIL = 'GET_ADOPT_FAIL'

export const UPDATE_ANIMALS_REQUEST = 'UPDATE_ANIMALS_REQUEST'
export const UPDATE_ANIMALS_SUCCESS = 'UPDATE_ANIMALS_SUCCESS'
export const UPDATE_ANIMALS_RESET = 'UPDATE_ANIMALS_RESET'
export const UPDATE_ANIMALS_FAIL = 'UPDATE_ANIMALS_FAIL'

export const DELETE_ANIMALS_REQUEST = 'DELETE_ANIMALS_REQUEST'
export const DELETE_ANIMALS_SUCCESS = 'DELETE_ANIMALS_SUCCESS'
export const DELETE_ANIMALS_RESET = 'DELETE_ANIMALS_RESET'
export const DELETE_ANIMALS_FAIL = 'DELETE_ANIMALS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
