
export const SINGLE_FREELANCER_REQUEST = 'SINGLE_FREELANCER_REQUEST'
export const SINGLE_FREELANCER_SUCCESS = 'SINGLE_FREELANCER_SUCCESS'
export const SINGLE_FREELANCER_FAIL = 'SINGLE_FREELANCER_SUCCESS'

export const NEW_FREELANCER_REQUEST = 'NEW_FREELANCER_REQUEST'
export const NEW_FREELANCER_SUCCESS = 'NEW_FREELANCER_SUCCESS'
export const NEW_FREELANCER_FAIL = 'NEW_FREELANCER_SUCCESS'
export const NEW_FREELANCER_RESET = 'NEW_FREELANCER_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
