export const NEW_INQUIRY_REQUEST = 'NEW_INQUIRY_REQUEST'
export const NEW_INQUIRY_SUCCESS = 'NEW_INQUIRY_SUCCESS'
export const NEW_INQUIRY_RESET =   'NEW_INQUIRY_RESET'
export const NEW_INQUIRY_FAIL =    'NEW_INQUIRY_FAIL'

export const ALL_INQUIRY_REQUEST = 'NEW_INQUIRY_REQUEST'
export const ALL_INQUIRY_SUCCESS = 'NEW_INQUIRY_SUCCESS'
export const ALL_INQUIRY_RESET =   'NEW_INQUIRY_RESET'
export const ALL_INQUIRY_FAIL =    'NEW_INQUIRY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
