export const NEW_OFFER_REQUEST = 'NEW_OFFER_REQUEST'
export const NEW_OFFER_SUCCESS = 'NEW_OFFER_SUCCESS'
export const NEW_OFFER_RESET = 'NEW_OFFER_RESET'
export const NEW_OFFER_FAIL = 'NEW_OFFER_FAIL'

export const GET_OFFERS_REQUEST = 'GET_OFFERS_REQUEST'
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS'
export const GET_OFFERS_RESET = 'GET_OFFERS_RESET'
export const GET_OFFERS_FAIL = 'GET_OFFERS_FAIL'

export const SINGLE_OFFER_REQUEST = 'SINGLE_OFFER_REQUEST'
export const SINGLE_OFFER_SUCCESS = 'SINGLE_OFFER_SUCCESS'
export const SINGLE_OFFER_RESET = 'SINGLE_OFFER_RESET'
export const SINGLE_OFFER_FAIL = 'SINGLE_OFFER_FAIL'

export const REQUEST_OFFERS_REQUEST = 'REQUEST_OFFERS_REQUEST'
export const REQUEST_OFFERS_SUCCESS = 'REQUEST_OFFERS_SUCCESS'
export const REQUEST_OFFERS_RESET = 'REQUEST_OFFERS_RESET'
export const REQUEST_OFFERS_FAIL = 'REQUEST_OFFERS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
