export const NEW_TRANSACTION_REQUEST = 'NEW_TRANSACTION_REQUEST'
export const NEW_TRANSACTION_SUCCESS = 'NEW_TRANSACTION_SUCCESS'
export const NEW_TRANSACTION_RESET = 'NEW_TRANSACTION_RESET'
export const NEW_TRANSACTION_FAIL = 'NEW_TRANSACTION_FAIL'

export const MY_FTRANSACTION_REQUEST = 'MY_FTRANSACTION_REQUEST'
export const MY_FTRANSACTION_SUCCESS = 'MY_FTRANSACTION_SUCCESS'
export const MY_FTRANSACTION_RESET = 'MY_FTRANSACTION_RESET'
export const MY_FTRANSACTION_FAIL = 'MY_FTRANSACTION_FAIL'

export const MY_CTRANSACTION_REQUEST = 'MY_CTRANSACTION_REQUEST'
export const MY_CTRANSACTION_SUCCESS = 'MY_CTRANSACTION_SUCCESS'
export const MY_CTRANSACTION_RESET = 'MY_CTRANSACTION_RESET'
export const MY_CTRANSACTION_FAIL = 'MY_CTRANSACTION_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
