export const NEW_TRANSACTION_REQUEST = 'NEW_TRANSACTION_REQUEST'
export const NEW_TRANSACTION_SUCCESS = 'NEW_TRANSACTION_SUCCESS'
export const NEW_TRANSACTION_RESET =   'NEW_TRANSACTION_RESET'
export const NEW_TRANSACTION_FAIL =    'NEW_TRANSACTION_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
